# Generated by Django 4.2.4 on 2023-08-16 15:17

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="A label for URL config",
                        max_length=31,
                        populate_from=["name"],
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=31)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="A label for URL config",
                        max_length=31,
                        populate_from=["name"],
                    ),
                ),
                ("description", models.TextField()),
                ("date_founded", models.DateField()),
                ("contact", models.EmailField(max_length=254)),
                ("website_link", models.URLField(max_length=255)),
                ("tags", models.ManyToManyField(to="organiser.tag")),
            ],
            options={"ordering": ["name"], "get_latest_by": "date_founded",},
        ),
        migrations.CreateModel(
            name="newsLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=31)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="A label for URL config",
                        max_length=31,
                        populate_from=["title"],
                    ),
                ),
                ("date_published", models.DateField()),
                ("article_link", models.URLField()),
                (
                    "startups",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organiser.startup",
                    ),
                ),
            ],
            options={
                "verbose_name": "news article",
                "ordering": ["-date_published"],
                "get_latest_by": "date_published",
                "unique_together": {("slug", "startups")},
            },
        ),
    ]
