# Generated by Django 4.2.4 on 2023-08-16 14:33

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organiser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                help_text="A label for URL config",
                max_length=31,
                populate_from=["name"],
            ),
        ),
    ]
