# Generated by Django 4.2.4 on 2023-08-16 14:40

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organiser", "0003_alter_newslink_slug_alter_startup_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=63)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="A label for URL config",
                        max_length=63,
                        populate_from=["title"],
                        unique=True,
                    ),
                ),
                ("text", models.Field()),
                ("pub_date", models.DateField(default=datetime.date.today)),
                ("Startups", models.ManyToManyField(to="organiser.startup")),
                ("tags", models.ManyToManyField(to="organiser.tag")),
            ],
            options={
                "verbose_name": "blog post",
                "ordering": ["-pub_date", "title"],
                "get_latest_by": "pub_date",
            },
        ),
    ]
